import type {
  User, SupplyListing, DemandRequest, Transaction, Payment,
  LogisticsJob, AuditEvent, Notification
} from '../types';
import { storageService, STORE_KEYS } from './storageService';

export function hashPassword(pw: string) {
  return `pwd_hash_${pw}`;
}

export const PLATFORM_IDS = {
  SUPPLIER_USER: 'USR-SUP-001',
  BUYER_USER: 'USR-BUY-001',
  LOGISTICS_USER: 'USR-LOG-001',
  ADMIN_USER: 'USR-ADM-001',
  LISTING: 'SUP-337',
  DEMAND: 'D-1043',
  TRANSACTION: 'TXN-4821',
  TRANSACTION_2: 'TXN-4804',
  TRANSACTION_3: 'TXN-4790',
  LOGISTICS_JOB: 'JOB-8871',
  REQUEST: 'REQ-2210',
};

export function seedInitialData(): void {
  const users: User[] = [
    {
      id: PLATFORM_IDS.BUYER_USER,
      email: 'buyer@kolafarms.com',
      passwordHash: hashPassword('agriflow123'),
      name: 'Kola Farms Ltd',
      role: 'buyer',
      organizationName: 'Kola Farms Ltd',
      phone: '+234 802 345 6789',
      location: 'Ikeja, Lagos',
      verified: true,
      profileComplete: true,
      createdAt: '2026-08-01T09:00:00.000Z',
    },
    {
      id: PLATFORM_IDS.SUPPLIER_USER,
      email: 'supplier@adeyemiproduce.com',
      passwordHash: hashPassword('agriflow123'),
      name: 'Adeyemi Produce Co.',
      role: 'supplier',
      organizationName: 'Adeyemi Produce Co.',
      phone: '+234 801 234 5678',
      location: 'Ogbomoso, Oyo State',
      verified: true,
      profileComplete: true,
      createdAt: '2026-08-01T08:00:00.000Z',
    },
    {
      id: 'USR-SUP-002',
      email: 'supplier@greendelta.com',
      passwordHash: hashPassword('agriflow123'),
      name: 'Green Delta Farms',
      role: 'supplier',
      organizationName: 'Green Delta Farms',
      phone: '+234 803 111 2233',
      location: 'Ilorin, Kwara State',
      verified: true,
      profileComplete: true,
      createdAt: '2026-08-05T09:00:00.000Z',
    },
    {
      id: 'USR-SUP-003',
      email: 'supplier@kadunagrain.com',
      passwordHash: hashPassword('agriflow123'),
      name: 'Kaduna Grain Union',
      role: 'supplier',
      organizationName: 'Kaduna Grain Union',
      phone: '+234 804 567 8901',
      location: 'Kaduna State',
      verified: true,
      profileComplete: true,
      createdAt: '2026-08-06T10:00:00.000Z',
    },
    {
      id: 'USR-SUP-004',
      email: 'supplier@ilorinagro.com',
      passwordHash: hashPassword('agriflow123'),
      name: 'Ilorin Agro Traders',
      role: 'supplier',
      organizationName: 'Ilorin Agro Traders',
      phone: '+234 805 777 8899',
      location: 'Kwara State',
      verified: false,
      profileComplete: true,
      createdAt: '2026-08-10T11:00:00.000Z',
    },
    {
      id: PLATFORM_IDS.LOGISTICS_USER,
      email: 'logistics@swifthaul.com',
      passwordHash: hashPassword('agriflow123'),
      name: 'SwiftHaul Logistics',
      role: 'logistics',
      organizationName: 'SwiftHaul Logistics',
      phone: '+234 803 456 7890',
      location: 'Lagos / Oyo / Kwara Corridor',
      verified: true,
      profileComplete: true,
      createdAt: '2026-08-01T10:00:00.000Z',
    },
    {
      id: PLATFORM_IDS.ADMIN_USER,
      email: 'admin@agriflow.trade',
      passwordHash: hashPassword('agriflow123'),
      name: 'AgriFlow Operations',
      role: 'admin',
      organizationName: 'AgriFlow',
      phone: '+234 800 000 0000',
      location: 'Lagos, Nigeria',
      verified: true,
      profileComplete: true,
      createdAt: '2026-07-01T00:00:00.000Z',
    },
  ];

  const listings: SupplyListing[] = [
    {
      id: PLATFORM_IDS.LISTING,
      supplierId: PLATFORM_IDS.SUPPLIER_USER,
      supplierName: 'Adeyemi Produce Co.',
      supplierVerified: true,
      commodity: 'maize',
      quantity: 18,
      unit: 'tonnes',
      qualityGrade: 'A',
      pricePerUnit: 480000,
      currency: 'NGN',
      location: 'Ogbomoso, Oyo State',
      availabilityDate: '2026-08-28T00:00:00.000Z',
      description: 'Grade A White Maize. Clean, dried to standard 12% moisture content. Ready for immediate pickup from Ogbomoso warehouse.',
      status: 'active',
      createdAt: '2026-08-20T08:00:00.000Z',
      updatedAt: '2026-08-20T08:00:00.000Z',
    },
    {
      id: 'SUP-338',
      supplierId: 'USR-SUP-002',
      supplierName: 'Green Delta Farms',
      supplierVerified: true,
      commodity: 'soybean',
      quantity: 12,
      unit: 'tonnes',
      qualityGrade: 'A',
      pricePerUnit: 465000,
      currency: 'NGN',
      location: 'Kwara State',
      availabilityDate: '2026-08-29T00:00:00.000Z',
      description: 'High-protein Non-GMO Soybeans, Grade A certified. Bagged in 50kg sacks.',
      status: 'active',
      createdAt: '2026-08-21T09:00:00.000Z',
      updatedAt: '2026-08-21T09:00:00.000Z',
    },
    {
      id: 'SUP-339',
      supplierId: 'USR-SUP-003',
      supplierName: 'Kaduna Grain Union',
      supplierVerified: true,
      commodity: 'sorghum',
      quantity: 40,
      unit: 'tonnes',
      qualityGrade: 'B',
      pricePerUnit: 441000,
      currency: 'NGN',
      location: 'Kaduna State',
      availabilityDate: '2026-08-25T00:00:00.000Z',
      description: 'Premium White Sorghum, Grade B. Tested and sorted for industrial and feed milling.',
      status: 'active',
      createdAt: '2026-08-22T10:00:00.000Z',
      updatedAt: '2026-08-22T10:00:00.000Z',
    },
    {
      id: 'SUP-340',
      supplierId: 'USR-SUP-004',
      supplierName: 'Ilorin Agro Traders',
      supplierVerified: false,
      commodity: 'maize',
      quantity: 12,
      unit: 'tonnes',
      qualityGrade: 'A',
      pricePerUnit: 502000,
      currency: 'NGN',
      location: 'Kwara State',
      availabilityDate: '2026-08-30T00:00:00.000Z',
      description: 'Fresh season White Maize, Grade A quality.',
      status: 'active',
      createdAt: '2026-08-23T11:00:00.000Z',
      updatedAt: '2026-08-23T11:00:00.000Z',
    },
  ];

  const demands: DemandRequest[] = [
    {
      id: PLATFORM_IDS.DEMAND,
      buyerId: PLATFORM_IDS.BUYER_USER,
      buyerName: 'Kola Farms Ltd',
      commodity: 'maize',
      quantity: 12,
      unit: 'tonnes',
      qualityGrade: 'A',
      destinationLocation: 'Ikeja, Lagos',
      requiredByDate: '2026-09-08T00:00:00.000Z',
      indicativeBudget: 6000000,
      currency: 'NGN',
      notes: 'White Maize Grade A. Required for food processing plant in Ikeja.',
      status: 'matched',
      createdAt: '2026-08-27T10:30:00.000Z',
      updatedAt: '2026-08-27T10:30:00.000Z',
    },
    {
      id: 'D-1044',
      buyerId: PLATFORM_IDS.BUYER_USER,
      buyerName: 'Kola Farms Ltd',
      commodity: 'soybean',
      quantity: 8,
      unit: 'tonnes',
      qualityGrade: 'A',
      destinationLocation: 'Ikeja, Lagos',
      requiredByDate: '2026-09-12T00:00:00.000Z',
      indicativeBudget: 4000000,
      currency: 'NGN',
      notes: 'Non-GMO grade A soybeans.',
      status: 'open',
      createdAt: '2026-08-26T09:00:00.000Z',
      updatedAt: '2026-08-26T09:00:00.000Z',
    },
  ];

  const transactions: Transaction[] = [
    {
      id: PLATFORM_IDS.TRANSACTION,
      listingId: PLATFORM_IDS.LISTING,
      demandId: PLATFORM_IDS.DEMAND,
      buyerId: PLATFORM_IDS.BUYER_USER,
      buyerName: 'Kola Farms Ltd',
      supplierId: PLATFORM_IDS.SUPPLIER_USER,
      supplierName: 'Adeyemi Produce Co.',
      commodity: 'maize',
      quantity: 12,
      unit: 'tonnes',
      qualityGrade: 'A',
      pricePerUnit: 480000,
      totalAmount: 6002600, // 5,760,000 + 185,000 logistics + 57,600 fee
      currency: 'NGN',
      pickupLocation: 'Ogbomoso, Oyo State',
      deliveryLocation: 'Ikeja, Lagos',
      expectedDeliveryDate: '2026-09-01T00:00:00.000Z',
      status: 'PAYMENT_PENDING',
      logisticsJobId: PLATFORM_IDS.LOGISTICS_JOB,
      history: [
        {
          status: 'PENDING',
          timestamp: '2026-08-27T13:58:00.000Z',
          actor: 'Kola Farms Ltd',
          actorRole: 'buyer',
          note: 'Request sent to supplier.',
        },
        {
          status: 'ACCEPTED',
          timestamp: '2026-08-27T14:15:00.000Z',
          actor: 'Adeyemi Produce Co.',
          actorRole: 'supplier',
          note: 'Supplier accepted transaction request.',
        },
        {
          status: 'PAYMENT_PENDING',
          timestamp: '2026-08-27T14:16:00.000Z',
          actor: 'AgriFlow System',
          actorRole: 'system',
          note: 'Awaiting payment confirmation from buyer.',
        },
      ],
      createdAt: '2026-08-27T13:58:00.000Z',
      updatedAt: '2026-08-27T14:16:00.000Z',
    },
    {
      id: PLATFORM_IDS.TRANSACTION_2,
      listingId: 'SUP-338',
      buyerId: PLATFORM_IDS.BUYER_USER,
      buyerName: 'Kola Farms Ltd',
      supplierId: 'USR-SUP-002',
      supplierName: 'Green Delta Farms',
      commodity: 'soybean',
      quantity: 8,
      unit: 'tonnes',
      qualityGrade: 'A',
      pricePerUnit: 465000,
      totalAmount: 3720000,
      currency: 'NGN',
      pickupLocation: 'Kwara State',
      deliveryLocation: 'Ikeja, Lagos',
      expectedDeliveryDate: '2026-08-31T16:00:00.000Z',
      status: 'IN_TRANSIT',
      logisticsJobId: 'JOB-8804',
      history: [
        {
          status: 'IN_TRANSIT',
          timestamp: '2026-08-27T09:30:00.000Z',
          actor: 'SwiftHaul Logistics',
          actorRole: 'logistics',
          note: 'En route to Ikeja, Lagos.',
        },
      ],
      createdAt: '2026-08-25T10:00:00.000Z',
      updatedAt: '2026-08-27T09:30:00.000Z',
    },
    {
      id: PLATFORM_IDS.TRANSACTION_3,
      listingId: 'SUP-339',
      buyerId: PLATFORM_IDS.BUYER_USER,
      buyerName: 'Kola Farms Ltd',
      supplierId: 'USR-SUP-003',
      supplierName: 'Kaduna Grain Union',
      commodity: 'sorghum',
      quantity: 20,
      unit: 'tonnes',
      qualityGrade: 'B',
      pricePerUnit: 441000,
      totalAmount: 8820000,
      currency: 'NGN',
      pickupLocation: 'Kaduna State',
      deliveryLocation: 'Ikeja, Lagos',
      expectedDeliveryDate: '2026-08-31T15:47:00.000Z',
      status: 'BUYER_CONFIRMATION_PENDING',
      logisticsJobId: 'JOB-8790',
      history: [
        {
          status: 'DELIVERED',
          timestamp: '2026-08-27T15:47:00.000Z',
          actor: 'SwiftHaul Logistics',
          actorRole: 'logistics',
          note: 'Delivered to Ikeja warehouse. Awaiting buyer confirmation.',
        },
      ],
      createdAt: '2026-08-24T08:00:00.000Z',
      updatedAt: '2026-08-27T15:47:00.000Z',
    },
  ];

  const logisticsJobs: LogisticsJob[] = [
    {
      id: PLATFORM_IDS.LOGISTICS_JOB,
      transactionId: PLATFORM_IDS.TRANSACTION,
      commodity: 'maize',
      quantity: 12,
      unit: 'tonnes',
      pickupLocation: 'Adeyemi Produce Co. · Ogbomoso, Oyo State',
      deliveryLocation: 'Kola Farms Ltd · Ikeja, Lagos',
      pickupDate: '2026-08-29T08:00:00.000Z',
      expectedDeliveryDate: '2026-09-01T16:00:00.000Z',
      logisticsCost: 185000,
      currency: 'NGN',
      providerId: PLATFORM_IDS.LOGISTICS_USER,
      providerName: 'SwiftHaul Logistics',
      status: 'ASSIGNED',
      createdAt: '2026-08-27T14:16:00.000Z',
      updatedAt: '2026-08-27T14:16:00.000Z',
    },
    {
      id: 'JOB-8804',
      transactionId: PLATFORM_IDS.TRANSACTION_2,
      commodity: 'soybean',
      quantity: 8,
      unit: 'tonnes',
      pickupLocation: 'Green Delta Farms · Kwara State',
      deliveryLocation: 'Kola Farms Ltd · Ikeja, Lagos',
      pickupDate: '2026-08-26T08:00:00.000Z',
      expectedDeliveryDate: '2026-08-31T16:00:00.000Z',
      logisticsCost: 145000,
      currency: 'NGN',
      providerId: PLATFORM_IDS.LOGISTICS_USER,
      providerName: 'SwiftHaul Logistics',
      status: 'IN_TRANSIT',
      createdAt: '2026-08-25T11:00:00.000Z',
      updatedAt: '2026-08-27T09:30:00.000Z',
    },
    {
      id: 'JOB-8790',
      transactionId: PLATFORM_IDS.TRANSACTION_3,
      commodity: 'sorghum',
      quantity: 20,
      unit: 'tonnes',
      pickupLocation: 'Kaduna Grain Union · Kaduna State',
      deliveryLocation: 'Kola Farms Ltd · Ikeja, Lagos',
      pickupDate: '2026-08-25T08:00:00.000Z',
      expectedDeliveryDate: '2026-08-27T15:47:00.000Z',
      logisticsCost: 280000,
      currency: 'NGN',
      providerId: PLATFORM_IDS.LOGISTICS_USER,
      providerName: 'SwiftHaul Logistics',
      status: 'DELIVERED',
      proofOfDelivery: {
        recipientName: 'Kola Farms Receiving Depot',
        deliveryNote: '20 tonnes of sorghum received in good condition, 400 sacks verified.',
        timestamp: '2026-08-27T15:47:00.000Z',
        recordedBy: 'SwiftHaul Driver LAG-448-XA',
      },
      createdAt: '2026-08-24T09:00:00.000Z',
      updatedAt: '2026-08-27T15:47:00.000Z',
    },
  ];

  const payments: Payment[] = [
    {
      id: 'PAY-4804',
      transactionId: PLATFORM_IDS.TRANSACTION_2,
      payerId: PLATFORM_IDS.BUYER_USER,
      amount: 3720000,
      currency: 'NGN',
      provider: 'AgriFlow Escrow Service',
      providerReference: 'ESC-4804-KOLA',
      status: 'CONFIRMED',
      createdAt: '2026-08-25T11:00:00.000Z',
      updatedAt: '2026-08-25T11:05:00.000Z',
      completedAt: '2026-08-25T11:05:00.000Z',
    },
    {
      id: 'PAY-4790',
      transactionId: PLATFORM_IDS.TRANSACTION_3,
      payerId: PLATFORM_IDS.BUYER_USER,
      amount: 8820000,
      currency: 'NGN',
      provider: 'AgriFlow Escrow Service',
      providerReference: 'ESC-4790-KOLA',
      status: 'CONFIRMED',
      createdAt: '2026-08-24T09:00:00.000Z',
      updatedAt: '2026-08-24T09:10:00.000Z',
      completedAt: '2026-08-24T09:10:00.000Z',
    },
  ];

  const notifications: Notification[] = [
    {
      id: 'NOTIF-001',
      userId: PLATFORM_IDS.SUPPLIER_USER,
      type: 'transaction_request',
      title: 'New Transaction Request',
      message: 'Kola Farms Ltd has sent a transaction request for 12 tonnes of White Maize (REQ-2210).',
      transactionId: PLATFORM_IDS.TRANSACTION,
      read: false,
      createdAt: '2026-08-27T13:58:00.000Z',
    },
    {
      id: 'NOTIF-002',
      userId: PLATFORM_IDS.BUYER_USER,
      type: 'transaction_accepted',
      title: 'Supplier Accepted Request',
      message: 'Adeyemi Produce Co. accepted your request for 12 tonnes of White Maize. Proceed to payment.',
      transactionId: PLATFORM_IDS.TRANSACTION,
      read: false,
      createdAt: '2026-08-27T14:15:00.000Z',
    },
    {
      id: 'NOTIF-003',
      userId: PLATFORM_IDS.LOGISTICS_USER,
      type: 'logistics_assigned',
      title: 'New Transport Job Assigned',
      message: 'You have been assigned transport job JOB-8871 (Ogbomoso to Ikeja, 12 tonnes White Maize).',
      transactionId: PLATFORM_IDS.TRANSACTION,
      read: false,
      createdAt: '2026-08-27T14:16:00.000Z',
    },
    {
      id: 'NOTIF-004',
      userId: PLATFORM_IDS.BUYER_USER,
      type: 'delivery_received',
      title: 'Shipment Delivered',
      message: 'Transaction TXN-4790 (Sorghum · 20t) has been delivered. Please inspect and confirm receipt.',
      transactionId: PLATFORM_IDS.TRANSACTION_3,
      read: false,
      createdAt: '2026-08-27T15:47:00.000Z',
    },
  ];

  const auditEvents: AuditEvent[] = [
    {
      id: 'AUD-001',
      action: 'supply_created',
      actorId: PLATFORM_IDS.SUPPLIER_USER,
      actorName: 'Adeyemi Produce Co.',
      actorRole: 'supplier',
      entityId: PLATFORM_IDS.LISTING,
      entityType: 'SupplyListing',
      detail: '18 tonnes of White Maize Grade A listed at ₦480,000/tonne from Ogbomoso, Oyo State.',
      createdAt: '2026-08-20T08:00:00.000Z',
    },
    {
      id: 'AUD-002',
      action: 'demand_created',
      actorId: PLATFORM_IDS.BUYER_USER,
      actorName: 'Kola Farms Ltd',
      actorRole: 'buyer',
      entityId: PLATFORM_IDS.DEMAND,
      entityType: 'DemandRequest',
      detail: 'Demand D-1043 created for 12 tonnes of White Maize, delivery to Ikeja, Lagos.',
      createdAt: '2026-08-27T10:30:00.000Z',
    },
    {
      id: 'AUD-003',
      action: 'match_generated',
      actorId: 'system',
      actorName: 'AgriFlow Match Engine',
      actorRole: 'system',
      entityId: PLATFORM_IDS.DEMAND,
      entityType: 'Match',
      detail: 'Matched Demand D-1043 with 4 active listings. Top match: Adeyemi Produce Co. (142 km, Grade A).',
      createdAt: '2026-08-27T10:31:00.000Z',
    },
    {
      id: 'AUD-004',
      action: 'transaction_initiated',
      actorId: PLATFORM_IDS.BUYER_USER,
      actorName: 'Kola Farms Ltd',
      actorRole: 'buyer',
      entityId: PLATFORM_IDS.TRANSACTION,
      entityType: 'Transaction',
      transactionId: PLATFORM_IDS.TRANSACTION,
      detail: 'Transaction TXN-4821 initiated for 12 tonnes of White Maize. Total due: ₦6,002,600.',
      createdAt: '2026-08-27T13:58:00.000Z',
    },
  ];

  storageService.set(STORE_KEYS.USERS, users);
  storageService.set(STORE_KEYS.LISTINGS, listings);
  storageService.set(STORE_KEYS.DEMANDS, demands);
  storageService.set(STORE_KEYS.TRANSACTIONS, transactions);
  storageService.set(STORE_KEYS.PAYMENTS, payments);
  storageService.set(STORE_KEYS.LOGISTICS_JOBS, logisticsJobs);
  storageService.set(STORE_KEYS.DISPUTES, []);
  storageService.set(STORE_KEYS.NOTIFICATIONS, notifications);
  storageService.set(STORE_KEYS.AUDIT_EVENTS, auditEvents);
  storageService.set(STORE_KEYS.SEEDED, true);
}

export function resetPlatformData(): void {
  storageService.clear();
  seedInitialData();
}
